RightCareer/RightCareer/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RightCareer.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index_Mobile()
        {
            return View("index_mobile");
        }
    }
}

RightCareer/RightCareer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="rightCareer">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script>
        var url;
        if ($(window).width() < 700) {
            url = '@Url.Action("Index_Mobile", "Index")';
        }
        else {
            url = '@Url.Action("Index", "Index")';
        }
        if (window.location.pathname != url) {
            window.location.href = url;
        }

        $(window).resize(function () {
            if ($(window).width() < 700) {
                url = '@Url.Action("Index_Mobile", "Index")';
            }
            else{
                url = '@Url.Action("Index", "Index")';
            }
            if (window.location.pathname != url) {
                window.location.href = url;
            }
        });
    </script>

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    <span class="text-center"><img alt="Brand" src="~/Images/logo.png" width="30" height="30" />&nbsp;&nbsp; Right Career</span>
                </a>
            </div>
        </div>
    </nav>
    <!--<div class="navbar-header">
        <div class="container-fluid navbar-text">
            
        </div>
    </div>-->
    @RenderBody()


    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)


</body>
</html>